version: '3.9'

services:
  api:
    build:
      context: ./API
    container_name: dataTourismAPI
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BLAZEGRAPH_HOSTNAME=bdd
    networks:
      - datatourismAPI
      - datatourismBDD

  bdd:
    image: conjecto/blazegraph:2.1.5
    container_name: dataTourismBDD
    restart: always
    ports:
      - 9999:9999
    environment:
      - JAVA_OPTS=-Xms2g -Xmx3g
    volumes:
      - ./API/dataset:/docker-entrypoint-initdb.d
    networks:
      - datatourismBDD

networks:
  datatourismAPI:
    driver: bridge
  datatourismBDD:
    driver: bridge
