version: '3.9'

services:
  api:
    build:
      context: ./API
    container_name: dataTourismAPI
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BLAZEGRAPH_HOSTNAME=bdd
    networks:
      - back

  bdd:
    image: openkbs/blazegraph:2.1.5
    container_name: dataTourismBDD
    restart: always
    ports:
      - 9999:9999
    volumes:
      - ./data:/var/lib/blazegraph/data
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
