version: '3.1'

services:

  api:
    build: .
    container_name: dataTourismAPI
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BLAZEGRAPH_HOSTNAME=bdd
    networks:
      - datatourism

  bdd:
    image: conjecto/blazegraph:2.1.5
    container_name: dataTourismBDD
    restart: always
    ports:
      - 9999:9999
    environment:
        JAVA_OPTS: "-Xms2g -Xmx3g"
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    networks:
      - datatourism

networks:
  datatourism:
    driver: bridge